// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hybdasleilusuvgxguvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5YmRhc2xlaWx1c3V2Z3hndXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzIwMDcsImV4cCI6MjA2NTY0ODAwN30.Qi7DSwyLwZ7qmZULYbtqY5CPbp8Hv4dX9mDFk_ISq8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);